import React, { useState } from "react";
import {
  Button,
  Container,
  TextField,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
} from "@mui/material";

const UserDataForm = () => {
  // State for user data
  const [formData, setFormData] = useState({
    id: Math.floor(Math.random() * 1000), // Autogenerated user ID
    name: "",
    address: "",
    email: "",
    phone: "",
  });

  // State for checking if form data has changed
  const [isDirty, setIsDirty] = useState(false);

  // Function to handle form input change
  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prevFormData) => ({
      ...prevFormData,
      [name]: value,
    }));
    setIsDirty(true); // Mark form as dirty
  };

  // Function to handle form submission
  const handleSubmit = (e) => {
    e.preventDefault();
    // Save form data to local storage or Redux Toolkit (RTK)
    localStorage.setItem("userData", JSON.stringify(formData));
    setIsDirty(false); // Reset dirty flag
    alert("Form data saved successfully!"); // Show confirmation message
  };

  // Function to handle displaying saved data
  const handleShowSavedData = () => {
    const savedData = localStorage.getItem("userData");
    alert(savedData ? savedData : "No data saved in local storage");
  };

  return (
    <Container maxWidth="sm">
      <form onSubmit={handleSubmit}>
        <TextField
          label="Name"
          name="name"
          value={formData.name}
          onChange={handleInputChange}
          fullWidth
          required
        />
        <TextField
          label="Address"
          name="address"
          value={formData.address}
          onChange={handleInputChange}
          fullWidth
          required
        />
        <TextField
          label="Email"
          name="email"
          value={formData.email}
          onChange={handleInputChange}
          fullWidth
          required
        />
        <TextField
          label="Phone"
          name="phone"
          value={formData.phone}
          onChange={handleInputChange}
          fullWidth
          required
        />
        <Button type="submit" variant="contained" style={{ marginTop: "10px" }}>
          Submit
        </Button>
        <Button
          onClick={handleShowSavedData}
          variant="contained"
          style={{ marginTop: "10px", marginLeft: "10px" }}
        >
          Show Saved Data
        </Button>
      </form>
    </Container>
  );
};

export default UserDataForm;
